[[redirects]]
  from = "/ingest/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  host = "us-assets.i.posthog.com"
  status = 200
  force = true

[[redirects]]
  from = "/ingest/*"
  to = "https://us.i.posthog.com/:splat"
  host = "us.i.posthog.com"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
